version: '3'

services:
  selectel_exporter:
    image: ustiuzhanin/selectel_billing_exporter
    container_name: selectel_exporter
    restart: unless-stopped
    ports:
      - "6789:5680"
    environment:
      TOKEN: ZKdqcDNQb8VE63cB9gv73U8Z6_40743
